name: Build and push images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push-windows:
    name: Build and push Windows image
    runs-on: windows-2025

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: lunacd/cimple-windows-x86_64

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build . -f dockerfiles/windows-x86_64.Dockerfile -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest --cache-from=type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  build-and-push-linux:
    name: Build and push Linux image
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: lunacd/cimple-linux-x86_64

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          context: .
          file: dockerfiles/linux-x86_64.Dockerfile
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,mode=max
